### ISSUE TITLE
Why can't ports be duplicated

### ISSUE THREAD

**Issue by luli440** [ChristianTremblay/BAC0#217]
![image](https://user-images.githubusercontent.com/66595084/90379857-deca8600-e0ad-11ea-8a29-6f3c1941abbe.png)

**Comment by ChristianTremblay** [comment]
Because BAC0 is a BACnet device on the network and must respond to other device if required. So as long as the instance is running, it captures the socket and listen for any request that come com from the network.

If you need more than one device per IP, you can use another port (47809 for example) or create another IP for the same network interface card.

**Comment by luli440** [comment]
Thank you very mush，There is one more question to ask
Is it possible to read different COM ports circularly and forward the same IP and port？
